{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.serviceAccount.name }}-binding"
  labels:
    app.kubernetes.io/name: "{{ .Values.serviceAccount.name }}-binding"
    app.kubernetes.io/component: lab-partner
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: helm
  annotations:
    description: Binds the lab-parter role to the lab-partner svc account
    source-repo: https://github.com/liatrio/lab-partner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
{{- end -}}
