apiVersion: v1
kind: Secret
metadata:
  name: lab-partner
type: Opaque
stringData:
  slackSigningSecret: {{ .Values.secrets.slackSigningSecret }}
  slackBotUserOauthAccessToken: {{ .Values.secrets.slackBotUserOauthAccessToken }}
  teamId: {{ .Values.secrets.teamId }}
