apiVersion: v1
kind: Secret
metadata:
  name: lab-partner
type: Opaque
stringData:
  slackSigningSecret: {{ .Values.secrets.slackSigningSecret }}
  slackBotUserOauthAccessToken: {{ .Values.secrets.slackBotUserOauthAccessToken }}
  teamId: {{ .Values.secrets.teamId }}
  mongoUri: mongodb://{{ .Values.mongodb.auth.custom_user.username }}:{{ .Values.mongodb.auth.custom_user.password }}@{{ .Values.mongodb.service.name }}:27017/{{ .Values.mongodb.auth.custom_user.database }}
