apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  slackSigningSecret: {{ .Values.image.secrets.slackSigningSecret }}
  slackBotUserOauthAccessToken: {{ .Values.image.secrets.slackBotUserOauthAccessToken }}
  teamId: {{ .Values.image.secrets.teamId }}
