apiVersion: v1
kind: Service
metadata:
  name: lab-partner
  labels:
    {{- include "lab-partner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lab-partner.selectorLabels" . | nindent 4 }}

