apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: lab-partner
      context: ./
  local: {}

deploy:
  helm:
    releases:
      - name: lab-partner
        chartPath: charts/lab-partner
        wait: true
        values:
          image.name: lab-partner

portForward:
  - resourceType: service
    resourceName: lab-partner
    port: 3000
