apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: liatrio/lab-partner
      context: ./
  local: {}

deploy:
  helm:
    releases:
      - name: lab-partner
        chartPath: charts/lab-partner
        wait: true
        artifactOverrides:
          image.name: liatrio/lab-partner
        setValueTemplates:
          secrets.slackSigningSecret: "{{ .SLACK_SIGNING_SECRET }}"
          secrets.slackBotUserOauthAccessToken: "{{ .SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}"
          secrets.teamId: "{{ .TEAM_ID }}"
          mongodb.auth.rootPassword: "{{ .MONGODB_PASSWORD }}"

portForward:
  - resourceType: service
    resourceName: lab-partner
    port: 3000

profiles:
  - name: local
    activation:
      - kubeContext: docker-for-desktop
      - kubeContext: docker-desktop
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value: 
          ingress.host: localhost

