apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: lab-partner
      context: ./
  local: {}

deploy:
  helm:
    releases:
      - name: lab-partner
        chartPath: charts/lab-partner
        wait: true
        setValueTemplates:
          image.name: lab-partner
          secrets.slackSigningSecret: "{{ .SLACK_SIGNING_SECRET }}"
          secrets.slackBotUserOauthAccessToken: "{{ .SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}"
          secrets.teamId: "{{ .TEAM_ID }}"

portForward:
  - resourceType: service
    resourceName: lab-partner
    port: 3000
