# Default values for lab-partner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mongodb:
  initdbScriptsConfigMap: lab-partner-mongodb-initdbscripts
  service:
    name: lab-partner-mongodb
  auth:
    custom_user:
      username: lab-partner
      database: lab-partner
      password:
  podLabels:
    app: mongodb

image: 
  name: liatrio/lab-partner
  pullPolicy: IfNotPresent
  
secrets:
    slackSigningSecret: ""
    slackBotUserOauthAccessToken: ""
    teamId: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: lab-partner

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  path: /
  tls: []
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


