# Default values for lab-partner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mongodb:
  initdbScriptsConfigMap: lab-partner-mongodb-initdbscripts
  service:
    name: lab-partner-mongodb
  auth:
    custom_user:
      username: lab-partner
      database: lab-partner
      password:

image: 
  name: liatrio/lab-partner
  pullPolicy: IfNotPresent
  
secrets:
    slackSigningSecret: ""
    slackBotUserOauthAccessToken: ""
    teamId: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: lab-partner.toolchain.lead.sandbox.liatr.io
  annotations:
    kubernetes.io/ingress.class: toolchain-nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  
  path: /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


