# Default values for lab-partner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mongodb:
  service:
    name: lab-partner-mongodb

image:
  name: lab-partner
  pullPolicy: IfNotPresent
  
secrets:
    slackSigningSecret: ""
    slackBotUserOauthAccessToken: ""
    teamId: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  host:
  tls: []
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


