name: deploy
on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - id: gitextra
      uses: liatrio/github-actions/git-extra@master
  
    - id: gitops
      uses: liatrio/github-actions/gitty-up@master
      with:
        url: https://github.com/liatrio/lead-environments.git
        username: ${{ github.actor }}
        password: ${{ secrets.GITTY_UP_TOKEN }}
        file: aws/manifest.yml
        values: liatrio_sandbox.lab_partner_version=${{steps.gitextra.outputs.version}}
    