name: build-docker-image
on: 
- push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200

    - id: ecr
      uses: liatrio/github-actions/ecr@master

    - id: skaffold
      uses: liatrio/github-actions/skaffold-build@master
      with:
        default_repo: ${{ steps.ecr.outputs.registry }}
