name: push
on: 
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - id: gitextra
      uses: liatrio/github-actions/git-extra@master

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200

    - name: Helm Chart
      uses: liatrio/github-actions/helm-push@master
      with:
        chart: charts/lab-partner
        bucket: liatrio-helm
        version: ${{steps.gitextra.outputs.version}}
        appVersion: ${{steps.gitextra.outputs.version}}
        dependencies: '[{"name":"mongodb","url":"https://charts.bitnami.com/bitnami"}]'

