name: Jon Runner Test

on: push

env:
  NODE_VERSION: '12.16.3'

jobs:
  runner-test:
    name: Runner Test

    runs-on: 
    - self-hosted
    - liatrio-runners-sand

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn
        run: npm install --global yarn

      - name: Run Tests
        run: |
          yarn
          yarn test

      - name: Run Linter
        run: yarn run lint
