name: test

on:
  push:

env:
  NODE_VERSION: '12.16.3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Tests
        run: |
          yarn
          yarn test
